on: push
name: Run Dusk testsuite
jobs:
  dusk-host:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4]
        laravel: [6.*]
        dependency-version: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

    - name: Redis Server in GitHub Actions
      uses: superchargejs/redis-github-action@1.1.0
      with:
        redis version: '4'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Prepare Laravel Application
      run: |
        php -r "file_exists('.env') || copy('.env.dusk.testing', '.env');"
        composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --optimize-autoloader
        php artisan key:generate

    - name: Create DB and schemas
      run: |
        mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS \`laravel\` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci";
        php artisan migrate:install
        php artisan migrate --seed

    - name: Compile assets
      run: |
        yarn install --pure-lockfile
        yarn run dev --progress false

    - name: Update Chrome Driver
      run: php artisan dusk:chrome-driver

    - name: Start Chrome Driver
      run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &

    - name: Run Laravel Server
      run: php artisan serve > /dev/null 2>&1 &

    - name: Run Dusk Tests
      run: php artisan dusk
